using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.EventSystems;
using UnityEngine.InputSystem.UI;
namespace CryptoMining {
public class WebGameUI:MonoBehaviour {
 GameManager g; MarketManager market; Font font; Canvas canvas; RectTransform screen,body,rack,modal,content,intro; Text money,coinIcon,coin,rate,cash,fork,temp,power,bill,fever,date,toast; float uiTick;
 readonly List<Action> live=new List<Action>(); readonly List<RectTransform> fans=new List<RectTransform>(); readonly List<Text> rackTemps=new List<Text>(); string rackKey="",page="",coolTarget=null,equipUid=null,selectedNode="root"; int pendingSlot=-1; Coroutine toastRoutine,typing; Text typed; string fullCaption; bool typingNow; int introIndex; bool replay;
 static readonly Color Bg=C("151a2c"),Panel=C("202a47"),Dark=C("0e1527"),Cyan=C("50dcff"),Green=C("79f17d"),Gold=C("ffd365"),Red=C("ff727d"),Muted=C("9aa7c5"),White=C("f2f5ff");
 static Color C(string s){Color c;ColorUtility.TryParseHtmlString("#"+s,out c);return c;}
 static Sprite fanSprite;
 static Sprite FanSprite(){if(fanSprite!=null)return fanSprite;var tex=new Texture2D(40,40,TextureFormat.RGBA32,false);tex.filterMode=FilterMode.Point;for(int y=0;y<40;y++)for(int x=0;x<40;x++){float dx=x-19.5f,dy=y-19.5f,r=Mathf.Sqrt(dx*dx+dy*dy),angle=Mathf.Atan2(dy,dx);Color c=Color.clear;if(r<19)c=C("121725");if(r>16&&r<19)c=C("77849b");if(r<15&&r>5&&Mathf.Sin(angle*7+r*.23f)>.05f)c=C("69798f");if(r<5)c=C("9ba7b9");tex.SetPixel(x,y,c);}tex.Apply();fanSprite=Sprite.Create(tex,new UnityEngine.Rect(0,0,40,40),new Vector2(.5f,.5f));return fanSprite;}
 static string N(double n){return Math.Floor(n).ToString("N0",CultureInfo.InvariantCulture);}
 static string D(double n){return n.ToString("0.0",CultureInfo.InvariantCulture);}
 void Awake(){g=GetComponent<GameManager>();if(g==null)g=gameObject.AddComponent<GameManager>();market=GetComponent<MarketManager>();if(market==null)market=gameObject.AddComponent<MarketManager>();}
 void Start(){font=Font.CreateDynamicFontFromOSFont(new[]{"Malgun Gothic","Apple SD Gothic Neo","Noto Sans CJK KR","Arial"},18);Build();g.Changed+=Refresh;g.Toast+=Toast;g.Overheated+=GameOver;market.Changed+=Refresh;market.Event+=News;market.ModalOpen=()=>modal!=null||intro!=null;Refresh();if(!g.S.running)GameOver();else if(PlayerPrefs.GetInt("webport_opening",0)==0)Opening(false);else if(PlayerPrefs.GetInt("webport_tutorial",0)==0)Tutorial();}
 void OnDestroy(){if(g!=null){g.Changed-=Refresh;g.Toast-=Toast;g.Overheated-=GameOver;}if(market!=null){market.Changed-=Refresh;market.Event-=News;}if(canvas!=null)Destroy(canvas.gameObject);}
 void Update(){foreach(var f in fans)if(f!=null)f.Rotate(0,0,-(g.Hottest()>=65?720:280)*Time.unscaledDeltaTime);uiTick+=Time.unscaledDeltaTime;if(uiTick>=.2f){uiTick=0;Refresh();}}
 RectTransform Rect(Transform p,string name,float x,float y,float w,float h){var r=new GameObject(name,typeof(RectTransform)).GetComponent<RectTransform>();r.SetParent(p,false);r.anchorMin=r.anchorMax=new Vector2(0,1);r.pivot=new Vector2(0,1);r.anchoredPosition=new Vector2(x,-y);r.sizeDelta=new Vector2(w,h);return r;}
 Image Paint(RectTransform r,Color c){var i=r.gameObject.AddComponent<Image>();i.color=c;return i;}
 RectTransform Box(Transform p,string name,float x,float y,float w,float h,Color c,Color? border=null,int bw=2){var r=Rect(p,name,x,y,w,h);Paint(r,border??c);if(border.HasValue){var fill=Rect(r,"Fill",bw,bw,w-bw*2,h-bw*2);Paint(fill,c).raycastTarget=false;}return r;}
 Text Text(Transform p,string value,float x,float y,float w,float h,int size=13,Color? color=null,TextAnchor align=TextAnchor.MiddleLeft){var r=Rect(p,value.Length>24?value.Substring(0,24):value,x,y,w,h);var t=r.gameObject.AddComponent<Text>();t.font=font;t.text=value;t.fontSize=size;t.color=color??White;t.alignment=align;t.raycastTarget=false;t.horizontalOverflow=HorizontalWrapMode.Wrap;t.verticalOverflow=VerticalWrapMode.Truncate;return t;}
 Button Button(Transform p,string label,float x,float y,float w,float h,Action action,Color? accent=null,int size=12){var c=accent??Green;var r=Box(p,label,x,y,w,h,C("1b3040"),c);var b=r.gameObject.AddComponent<Button>();b.targetGraphic=r.GetComponent<Image>();b.interactable=action!=null;if(action!=null)b.onClick.AddListener(()=>action());var colors=b.colors;colors.disabledColor=new Color(.35f,.35f,.35f,.6f);colors.pressedColor=new Color(.6f,.7f,.8f);b.colors=colors;Text(r,label,4,2,w-8,h-4,size,White,TextAnchor.MiddleCenter);return b;}
 void Fill(RectTransform r){r.anchorMin=Vector2.zero;r.anchorMax=Vector2.one;r.offsetMin=r.offsetMax=Vector2.zero;}
 RectTransform Scroll(Transform p,float x,float y,float w,float h,out ScrollRect sc){var outer=Rect(p,"Scroll",x,y,w,h);sc=outer.gameObject.AddComponent<ScrollRect>();var vp=Rect(outer,"Viewport",0,0,w,h);Paint(vp,new Color(0,0,0,0));vp.gameObject.AddComponent<RectMask2D>();var cr=Rect(vp,"Content",0,0,w,0);sc.viewport=vp;sc.content=cr;sc.horizontal=false;sc.movementType=ScrollRect.MovementType.Clamped;sc.scrollSensitivity=35;return cr;}
 void Build(){if(FindFirstObjectByType<EventSystem>()==null)new GameObject("EventSystem",typeof(EventSystem),typeof(InputSystemUIInputModule));var cv=new GameObject("Web Game Canvas",typeof(Canvas),typeof(CanvasScaler),typeof(GraphicRaycaster));canvas=cv.GetComponent<Canvas>();canvas.renderMode=RenderMode.ScreenSpaceOverlay;canvas.pixelPerfect=true;var scaler=cv.GetComponent<CanvasScaler>();scaler.uiScaleMode=CanvasScaler.ScaleMode.ScaleWithScreenSize;scaler.referenceResolution=new Vector2(480,854);scaler.screenMatchMode=CanvasScaler.ScreenMatchMode.Expand;var backdrop=Rect(cv.transform,"Backdrop",0,0,480,854);Fill(backdrop);Paint(backdrop,C("0b101d"));screen=Box(cv.transform,"Mobile 480 x 854",0,0,480,854,Bg);screen.anchorMin=screen.anchorMax=new Vector2(.5f,.5f);screen.pivot=new Vector2(.5f,.5f);screen.anchoredPosition=Vector2.zero;
 ScrollRect scroll;body=Scroll(screen,0,0,480,774,out scroll);body.sizeDelta=new Vector2(480,817);Paint(body,C("303a54"));for(int i=0;i<35;i++){Box(body,"Grid",i*14,0,1,817,new Color(1,1,1,.025f));}for(int i=0;i<59;i++)Box(body,"Grid",0,i*14,480,1,new Color(1,1,1,.025f));
 date=Text(body,"",10,6,450,19,11);Text(body,"『암호화폐 마이닝』",60,28,340,30,19,White,TextAnchor.MiddleCenter);Button(body,"▶",397,28,30,30,()=>Opening(true),Gold);Button(body,"?",436,28,30,30,Tutorial,Cyan,16);
 var hud=Box(body,"HUD",9,66,462,234,C("253150"),C("56658c"),3);var wallet=Box(hud,"Wallet",10,10,442,62,C("1b2440"),C("425078"));coinIcon=Text(wallet,"₿",10,6,38,44,34,Gold);money=Text(wallet,"0",53,3,240,38,27);coin=Text(wallet,"BTC-X 채굴 중",53,39,225,17,11,Cyan);rate=Text(wallet,"+1.0 / sec",287,18,142,28,14,Green,TextAnchor.MiddleRight);
 var f=Box(hud,"Fever",10,80,442,34,C("684113"),C("f2b451"));fever=Text(f,"",5,2,432,30,12,Gold,TextAnchor.MiddleCenter);
 var cashBox=Box(hud,"Cash",10,122,218,34,Dark,C("465375"));cash=Text(cashBox,"",10,3,198,28,13);var forkBox=Box(hud,"Fork",234,122,218,34,Dark,C("465375"));fork=Text(forkBox,"",10,3,198,28,13,Green,TextAnchor.MiddleRight);
 var t=Box(hud,"Temp",10,164,143,60,Dark,C("465375"));Text(t,"TEMP",8,5,127,18,11,Muted);temp=Text(t,"",8,25,127,26,15);
 var p=Box(hud,"Power",160,164,142,60,Dark,C("465375"));Text(p,"POWER",8,5,126,18,11,Muted);power=Text(p,"",8,25,126,26,15,Gold);
 var e=Box(hud,"Electricity",309,164,143,60,Dark,C("465375"));Text(e,"ELECTRICITY",8,5,127,18,10,Muted);bill=Text(e,"",8,25,127,26,13,Red);
 var room=Box(body,"Mining Room",9,309,462,500,C("cbb8a8"),C("88746f"),3);Box(room,"Floor",3,320,456,177,C("ded0c2"));Box(room,"Wood trim",3,3,456,18,C("654533"));rack=Box(room,"Rack",8,163,224,322,C("626775"),C("30343d"),4);
 var desk=Rect(room,"Trading Desk",252,266,192,220);Box(desk,"Desk top",0,85,192,32,C("71623d"));Box(desk,"Left leg",8,112,38,108,C("71623d"));Box(desk,"Right leg",146,112,38,108,C("71623d"));Box(desk,"Monitor stand",82,60,28,42,C("3b4155"));var monitor=Button(desk,"",49,0,94,69,()=>Open("trade"),C("737988"));var mr=monitor.GetComponent<RectTransform>();Box(mr,"Screen",7,7,80,55,C("070e13")).GetComponent<Image>().raycastTarget=false;Text(mr,"₿",7,7,80,34,27,Green,TextAnchor.MiddleCenter);Text(mr,"코인 판매",7,40,80,17,10,Green,TextAnchor.MiddleCenter);
 var nav=Box(screen,"Bottom Navigation",0,774,480,80,C("090f1e"),C("56658c"));string[] names={"GPU","INV","OC","COOL","SHOP","FORK"},icons={"▣","▤","↗","❄","＋","⋈"},pages={"gpu","inventory","oc","cool","shop","fork"};for(int i=0;i<6;i++){string key=pages[i];Button(nav,icons[i]+"\n["+names[i]+"]",5+i*79,7,74,65,()=>{pendingSlot=-1;Open(key);},C("56658c"),12);}
 toast=Text(screen,"",20,714,440,48,13,White,TextAnchor.MiddleCenter);toast.gameObject.AddComponent<Outline>().effectColor=Bg;toast.transform.SetAsLastSibling();toast.gameObject.SetActive(false);
 }
 void Refresh(){if(money==null||g.S==null)return;var c=g.MiningCoin();coinIcon.text=new[]{"₿","Ξ","Ð","✦","404","Q"}[Array.IndexOf(Catalog.Coins,c)];money.text=N(g.Balance(c.id));coin.text=c.name+" 채굴 중";rate.text="+"+D(g.TotalAuto())+" / sec";cash.text="₩ 현금 "+N(g.S.cash);fork.text="⋈ FORK "+g.S.fork;temp.text=Mathf.FloorToInt(g.Hottest())+"°C";temp.color=g.Hottest()>=85?Red:g.Hottest()>=65?Gold:White;power.text=g.TotalPower()+"W";bill.text="-₩"+g.ElectricityPerMinute()+"/min";fever.text=g.S.fever?"◆ MINING FEVER | ×"+(g.HasFork("fever")?3:2)+" | "+g.S.feverTime+"s ◆":"◆ MINING FEVER | CHARGING | "+g.S.feverCooldown+"s ◆";date.text=DateTime.UtcNow.AddHours(9).ToString("yyyy. MM. dd. HH:mm:ss")+" · 한국 시간";
 string key="";for(int i=0;i<8;i++){var it=g.At(i);key+=it==null?"-":it.uid+":"+it.modelId+":"+it.coolerId;key+="|";}if(key!=rackKey){rackKey=key;BuildRack();}for(int i=0;i<rackTemps.Count;i++)if(rackTemps[i]!=null){var gpu=g.At(i);rackTemps[i].text=gpu==null?"":Mathf.FloorToInt(gpu.temp)+"°C";}foreach(var update in live.ToArray())update();}
 void BuildRack(){foreach(Transform child in rack)Destroy(child.gameObject);fans.Clear();rackTemps.Clear();for(int i=0;i<8;i++){int slot=i;var gpu=g.At(i);float x=10+(i%2)*106,y=12+(i/2)*76;var b=Button(rack,gpu==null?"[추가하기]":"",x,y,98,68,gpu==null?(Action)(()=>{pendingSlot=slot;Open("shop");}):()=>{double gain=g.ClickMine(gpu.uid);if(gain>0)FloatGain(gain);},gpu==null?C("29412e"):C("414c61"),10);var r=b.GetComponent<RectTransform>();Box(r,"LED",9,60,80,3,Green).GetComponent<Image>().raycastTarget=false;if(gpu==null){rackTemps.Add(null);continue;}var model=Catalog.GPU(gpu.modelId);Text(r,model.name,5,3,89,12,8,Muted);rackTemps.Add(Text(r,"",61,15,31,11,8,Cyan,TextAnchor.MiddleRight));if(gpu.coolerId>=3){var water=Box(r,"Waterblock",12,28,74,28,C("10465c"),Cyan);water.GetComponent<Image>().raycastTarget=false;Text(water,"◈ WATER",2,2,70,24,11,Cyan,TextAnchor.MiddleCenter);}else for(int f=0;f<2;f++){var fan=Rect(r,"Fan",11+f*42,27,32,29);fan.pivot=new Vector2(.5f,.5f);fan.anchoredPosition+=new Vector2(16,-14.5f);var symbol=Rect(fan,"Fan blades",-16,-14,32,29);var image=Paint(symbol,Color.white);image.sprite=FanSprite();image.raycastTarget=false;fans.Add(fan);}}}
 void FloatGain(double n){var t=Text(screen,"+"+N(n)+" "+g.MiningCoin().name,45,470,220,32,19,Green,TextAnchor.MiddleCenter);StartCoroutine(FloatRoutine(t));}
 IEnumerator FloatRoutine(Text t){float a=0;while(a<.9f){a+=Time.unscaledDeltaTime;t.rectTransform.anchoredPosition+=Vector2.up*35*Time.unscaledDeltaTime;t.color=new Color(Green.r,Green.g,Green.b,1-a/.9f);yield return null;}Destroy(t.gameObject);}
 void Toast(string s){if(toastRoutine!=null)StopCoroutine(toastRoutine);toastRoutine=StartCoroutine(ToastTime(s));}
 IEnumerator ToastTime(string s){toast.text=s;toast.transform.SetAsLastSibling();toast.gameObject.SetActive(true);yield return new WaitForSecondsRealtime(1.6f);toast.gameObject.SetActive(false);}
 float y; RectTransform Card(string title,string detail,float h=110){var r=Box(content,title,0,y,412,h,Dark,C("394765"));Text(r,title,10,7,392,26,14,Green);Text(r,detail,10,37,392,h-44,12);y+=h+9;return r;}
 void ActionCard(string title,string detail,string label,Action a,Color? accent=null,float h=158){var r=Card(title,detail,h);Button(r,label,10,h-44,392,34,a,accent);}
 void LiveText(Text t,Func<string> f){Action a=()=>{if(t!=null)t.text=f();};live.Add(a);a();}
 void Open(string type){if(!g.S.running)return;Close(false);page=type;string title=type=="gpu"?"GPU MANAGER":type=="inventory"?"GPU INVENTORY":type=="oc"?"OVERCLOCK":type=="cool"?"GPU COOLING LAB":type=="shop"?"HARDWARE SHOP":type=="fork"?"FORK UPGRADE TREE":type=="news"?"코인 시장 속보":"MULTI COIN EXCHANGE";
 modal=Box(screen,"Modal",0,0,480,854,new Color(.01f,.02f,.05f,.94f));var box=Box(modal,"Popup",20,32,440,746,Panel,C("56658c"),3);Text(box,title,12,8,354,35,16,Cyan);Button(box,"×",387,8,40,35,()=>Close(),Red,22);ScrollRect sc;content=Scroll(box,14,55,412,675,out sc);y=0;
 switch(type){case "gpu":GPU();break;case "inventory":Inventory();break;case "oc":OC();break;case "cool":Cool();break;case "shop":Shop();break;case "fork":Fork();break;case "trade":Trade();break;case "news":NewsContent();break;}content.sizeDelta=new Vector2(412,y+8);Refresh();}
 public void Close(bool reset=true){live.Clear();if(modal!=null){modal.gameObject.SetActive(false);Destroy(modal.gameObject);}modal=null;page="";if(reset){pendingSlot=-1;equipUid=null;coolTarget=null;}}
 string Certification(){int t=g.RigTier();if(t==8)return "QUANTUM 인증 완료 · 모든 GPU 등급 해금";var n=Catalog.GPUs[t+1];return "현재 "+Catalog.GPUs[t].name+" 인증 · 다음 "+n.name+"\n운영 "+g.Duration(g.S.runSeconds)+" / "+g.Duration(g.RequiredSeconds(n))+"\n누적 채굴 "+N(g.S.totalMined)+" / "+N(n.unlockMined);}
 void GPU(){Card("RIG STATUS",g.Equipped().Count+"/8 GPU ONLINE\nTOTAL HASH "+D(g.TotalHash())+" H/s · AUTO "+D(g.TotalAuto())+"/sec\nPOWER "+g.TotalPower()+"W");Card("RIG CERTIFICATION",Certification(),123);var primary=g.At(0);var next=primary!=null&&primary.modelId<8?Catalog.GPUs[primary.modelId+1]:null;ActionCard("1번 슬롯 업그레이드",next==null?"1번 슬롯 GPU가 없거나 최종 등급입니다.":Catalog.GPU(primary.modelId).name+" → "+next.name+"\n₩"+N(Catalog.GPU(primary.modelId).upgradeCost),"[ 업그레이드 ]",next!=null?(Action)(()=>{g.UpgradePrimary();Open("gpu");}):null);for(int i=0;i<8;i++){int slot=i;var it=g.At(i);ActionCard("SLOT "+(i+1),it==null?"EMPTY":Catalog.GPU(it.modelId).name+"\nTEMP "+Mathf.FloorToInt(it.temp)+"°C · "+Catalog.Cooler(it.coolerId).name,it==null?"[ GPU 추가하기 ]":"[ 인벤토리로 이동 ]",()=>{if(it==null){pendingSlot=slot;Open("shop");}else{g.Unequip(it.uid);Open("gpu");}});}}
 void Inventory(){Card("INVENTORY","보유 GPU "+g.S.items.Count+"개\n장착 "+g.Equipped().Count+" / 보관 "+(g.S.items.Count-g.Equipped().Count));if(equipUid!=null){Card("장착 슬롯 선택",Catalog.GPU(g.Find(equipUid).modelId).name+" · 점유된 슬롯을 선택하면 기존 GPU는 보관됩니다.",86);for(int i=0;i<8;i++){int slot=i;var old=g.At(i);Button(content,"SLOT "+(i+1)+" · "+(old==null?"EMPTY":Catalog.GPU(old.modelId).name),(i%2)*210,y,202,50,()=>{g.Equip(equipUid,slot);equipUid=null;Open("inventory");},old==null?Cyan:Gold,11);if(i%2==1)y+=58;}Button(content,"취소",0,y,412,36,()=>{equipUid=null;Open("inventory");},Red);y+=45;}
 foreach(var it in g.S.items){var model=Catalog.GPU(it.modelId);ActionCard(model.name+(it.slot>=0?" · SLOT "+(it.slot+1):" · 보관"),D(model.hash)+" H/s · "+model.power+"W\nTEMP "+Mathf.FloorToInt(it.temp)+"°C · "+Catalog.Cooler(it.coolerId).name,it.slot<0?"장착":"해제",()=>{if(it.slot<0)equipUid=it.uid;else g.Unequip(it.uid);Open("inventory");});}}
 void OC(){ActionCard("OVERCLOCK STATUS · "+(g.S.overclock?"ACTIVE":"OFF"),"현재 자동 채굴 "+D(g.TotalAuto())+"/sec\nOC BONUS +"+(g.HasFork("oc")?50:30)+"%\n성능과 장착 GPU의 발열 속도가 함께 증가합니다.",g.S.overclock?"[ OVERCLOCK OFF ]":"[ OVERCLOCK ON ]",()=>{g.ToggleOC();if(g.S.running)Open("oc");},Gold,180);}
 void Cool(){var r=ActionCardTemp();foreach(var it in g.Equipped())ActionCard("SLOT "+(it.slot+1)+" · "+Catalog.GPU(it.modelId).name,"TEMP "+Mathf.FloorToInt(it.temp)+"°C\n"+Catalog.Cooler(it.coolerId).name,it.uid==coolTarget?"선택됨":"변경",()=>{coolTarget=it.uid;Open("cool");},Cyan);
 var target=g.Find(coolTarget);if(target!=null&&target.slot>=0){ActionCard("선택 GPU · "+Catalog.GPU(target.modelId).name,"현재: "+Catalog.Cooler(target.coolerId).name,"[ 기본 듀얼팬 장착 ]",()=>{g.StockCooler(target.uid);Open("cool");});foreach(var unit in g.S.coolingItems){var mounted=g.Find(unit.gpuUid);ActionCard(Catalog.Cooler(unit.coolerId).name,unit.gpuUid==null?"보관":mounted==null?"보관":Catalog.GPU(mounted.modelId).name+" 장착","장착",unit.gpuUid==target.uid?null:(Action)(()=>{g.EquipCooler(unit.uid,target.uid);Open("cool");}));}}
 foreach(var cl in Catalog.Coolers){if(cl.id==0)continue;bool unlocked=g.CoolerUnlocked(cl);ActionCard(cl.name,cl.desc+"\n자동 냉각 -"+(cl.rate*(g.HasFork("cooling")?1.15:1)).ToString("0.00")+"°C/s · ₩"+N(cl.cost)+"\n"+(unlocked?"인증 완료":"운영 "+g.Duration(Mathf.FloorToInt(cl.unlockSeconds*g.CycleFactor()))+" 후 해금"),unlocked?"구매":"잠금",unlocked&&g.S.cash>=cl.cost?(Action)(()=>{g.BuyCooler(coolTarget,cl.id);Open("cool");}):null,null,185);}}
 RectTransform ActionCardTemp(){var r=Card("RACK TEMPERATURE","냉각장치는 GPU마다 따로 장착됩니다.\n100°C 도달 시 파산합니다.",180);var t=Text(r,"",10,84,392,36,13,Cyan);LiveText(t,()=>"최고 "+Mathf.FloorToInt(g.Hottest())+"°C · 장착 GPU "+g.Equipped().Count+"개");Button(r,"[ 랙 전체 긴급 냉각 ]",10,134,392,34,()=>{g.EmergencyCool();},Cyan);return r;}
 void Shop(){Card("RIG CERTIFICATION",Certification()+"\n"+(pendingSlot>=0?"SLOT "+(pendingSlot+1)+"에 바로 장착":"구매한 GPU는 인벤토리에 보관됩니다.")+"\n보유 ₩"+N(g.S.cash),158);foreach(var m in Catalog.GPUs){bool u=g.Certified(m);ActionCard(m.name,"CLICK "+N(m.click)+" · AUTO "+D(m.autoMine)+"/s · "+m.power+"W\n가격 ₩"+N(m.price)+"\n"+(u?"해금됨":"운영 "+g.Duration(g.RequiredSeconds(m))+" + 누적 "+N(m.unlockMined)),u?"구매":"잠금",u&&g.S.cash>=m.price?(Action)(()=>{if(g.BuyGpu(m.id,pendingSlot))pendingSlot=-1;Open("shop");}):null,null,176);}}
 static readonly string[] ids={"root","cooling","click","auto","oc","fork","fever"},nodeNames={"MINING CORE","THERMAL SHIELD","CLICK ENGINE","AUTO HASH","STABLE OC","MINING MASTERY","FEVER CORE"},req={"","root","root","root","click","auto","cooling"},desc={"모든 FORK 업그레이드의 시작점입니다.","모든 장착 GPU의 발열을 20% 감소시키고 냉각을 강화합니다.","GPU 클릭 채굴량이 25% 증가합니다.","랙 전체 자동 채굴량이 30% 증가합니다.","오버클럭 보너스를 +30%에서 +50%로 강화합니다.","클릭 및 자동 채굴 수익이 영구적으로 10% 증가합니다.","FEVER 배율을 ×2에서 ×3으로, 지속시간을 25초로 강화합니다."};
 void Fork(){ActionCard("환생 · 완료 "+g.S.rebirths+"회","QUANTUM "+g.QuantumCount()+" / "+g.RebirthReq()+" · 운영 "+g.Duration(g.S.runSeconds)+" / "+g.Duration(g.RebirthSeconds())+"\n초기화: 돈, GPU, 쿨러, 이번 회차 기록\n유지: 환생 횟수, FORK, 해금한 업그레이드","[ 환생 · FORK +1 ]",g.CanRebirth()?(Action)(()=>{g.Rebirth();Open("fork");}):null,C("d383ff"),190);Card("FORK NETWORK","보유 FORK "+g.S.fork+" · 각 노드 해금 비용 1",80);var tree=Box(content,"Tech Tree",0,y,412,430,C("0d0f12"),C("343945"));float[] xs={177,79,79,275,275,177,177},ys={177,86,270,86,270,28,326};for(int i=1;i<7;i++){int parent=Array.IndexOf(ids,req[i]);Line(tree,new Vector2(xs[parent]+29,ys[parent]+29),new Vector2(xs[i]+29,ys[i]+29),g.HasFork(ids[i])?Green:C("777d86"),3);}for(int i=0;i<7;i++){int j=i;bool have=g.HasFork(ids[i]);bool available=have||g.HasFork(req[i]);Button(tree,new[]{"CORE","SHIELD","CLICK","AUTO","OC","FORK","FEVER"}[i]+"\n"+(i==0?"":"1"),xs[i],ys[i],58,58,()=>{selectedNode=ids[j];Open("fork");},selectedNode==ids[i]?Cyan:have?Green:available?Gold:C("353b48"),9);}y+=439;int k=Array.IndexOf(ids,selectedNode);ActionCard(nodeNames[k],desc[k]+"\nCOST : "+(k==0?0:1)+" FORK",g.HasFork(selectedNode)?"UNLOCKED":!g.HasFork(req[k])?"선행 노드 필요":"[ 업그레이드 해금 ]",!g.HasFork(selectedNode)&&g.HasFork(req[k])&&g.S.fork>=1?(Action)(()=>{g.BuyFork(ids[k],req[k]);Open("fork");}):null,C("d383ff"));}
 void Line(Transform p,Vector2 a,Vector2 b,Color c,float width){Vector2 delta=b-a;var r=Box(p,"Line",a.x,a.y,delta.magnitude,width,c);r.pivot=new Vector2(0,.5f);r.localRotation=Quaternion.Euler(0,0,-Mathf.Atan2(delta.y,delta.x)*Mathf.Rad2Deg);r.GetComponent<Image>().raycastTarget=false;}
 void Trade(){Card("코인 선택","상위 GPU 구매/업그레이드로 새 코인 해금\n현재 채굴: "+g.MiningCoin().name,86);for(int i=0;i<Catalog.Coins.Length;i++){var c=Catalog.Coins[i];bool u=g.CoinUnlocked(c);float x=(i%2)*210;var tile=Box(content,c.name,x,y,202,112,Dark,g.S.tradeCoinId==c.id?Cyan:C("405071"));Text(tile,c.name,8,6,186,23,13,Cyan);var quote=Text(tile,"",8,31,186,39,11);LiveText(quote,()=>u?"₩"+market.Price(c.id).ToString("0.000")+" · 보유 "+D(g.Balance(c.id)):Catalog.GPU(c.unlockGpu).name+" 보유 시 해금");Button(tile,"차트",8,75,88,29,u?(Action)(()=>{g.SetTradeCoin(c.id);Open("trade");}):null,Cyan,10);Button(tile,g.S.miningCoinId==c.id?"채굴중":"채굴",104,75,90,29,u?(Action)(()=>{g.SetMiningCoin(c.id);Open("trade");}):null,null,10);if(i%2==1)y+=120;}
 g.EnsureContract();var q=g.S.contract;var contract=Card("MINING CONTRACT · 완료 "+g.S.contractsCompleted,"",155);var qt=Text(contract,"",10,37,392,68,12);LiveText(qt,()=>(q.type=="mine"?"채굴":"판매")+" 계약 · "+Catalog.Coin(q.coinId).name+"\n"+N(q.progress)+" / "+N(q.target)+" · 보상 ₩"+N(q.reward));var claim=Button(contract,"[ 계약 보상 받기 ]",10,110,392,34,()=>{g.ClaimContract();Open("trade");},C("d383ff"));live.Add(()=>claim.interactable=q.progress>=q.target);
 string id=g.S.tradeCoinId;var chartBox=Card(Catalog.Coin(id).name+" / 원 · 5초봉","",275);var price=Text(chartBox,"",10,32,392,27,17,Gold);LiveText(price,()=>"₩"+market.Price(id).ToString("0.000"));var chart=Rect(chartBox,"Candlestick Chart",10,65,392,165).gameObject.AddComponent<CandleChart>();chart.market=market;chart.coinId=id;var stats=Text(chartBox,"",10,233,392,33,11,Muted);LiveText(stats,()=>"다음 시세 "+Mathf.CeilToInt(market.Countdown)+"초 · 보유 "+D(g.Balance(id))+"\n전량 판매 예상 ₩"+N(g.Balance(id)*market.Price(id)));live.Add(()=>chart.SetVerticesDirty());
 Text(content,"판매할 "+Catalog.Coin(id).name+" 수량",0,y,412,26,13);y+=30;var inputRect=Box(content,"판매 수량",0,y,412,45,Dark,Cyan);var input=inputRect.gameObject.AddComponent<InputField>();input.textComponent=Text(inputRect,"",10,4,392,37,17);input.placeholder=Text(inputRect,"판매 수량 입력",10,4,392,37,14,Muted);input.contentType=InputField.ContentType.DecimalNumber;y+=54;var estimate=Text(content,"",0,y,412,30,12,Gold);y+=38;LiveText(estimate,()=>{double amount;return double.TryParse(input.text,NumberStyles.Float,CultureInfo.InvariantCulture,out amount)&&!double.IsInfinity(amount)&&!double.IsNaN(amount)?"예상 수령 ₩"+N(amount*market.Price(id)):"수량을 입력하세요.";});Button(content,"[ 입력 수량 판매 ]",0,y,412,40,()=>{double a;if(double.TryParse(input.text,NumberStyles.Float,CultureInfo.InvariantCulture,out a)&&g.Sell(id,a))Open("trade");else Toast("판매 수량과 보유 코인을 확인하세요.");},Cyan);y+=49;var all=Button(content,"[ "+Catalog.Coin(id).name+" 전량 판매 ]",0,y,412,40,()=>{g.Sell(id,g.Balance(id));Open("trade");});live.Add(()=>all.interactable=g.Balance(id)>0);y+=49;}
 void News(string message){Open("news");}
 void NewsContent(){Card("게임 속 가상 시장 이벤트",market.LastEvent+"\n이 게임의 코인은 모두 가상이며 실제 자산과 관계없습니다.",170);Button(content,"[ 거래소 보기 ]",0,y,412,42,()=>Open("trade"),Gold);y+=52;Button(content,"[ 확인 ]",0,y,412,42,()=>Close(),Cyan);y+=52;}
 void GameOver(){Close();StopIntro();intro=Box(screen,"System Failure",0,0,480,854,new Color(.03f,.01f,.02f,.98f));var b=Box(intro,"Failure",40,230,400,360,C("35121c"),Red,4);Text(b,"SYSTEM FAILURE",18,18,364,46,22,Red,TextAnchor.MiddleCenter);Text(b,"그래픽카드 과열로 인한 파산!\n\n장착 GPU 중 하나가 100°C에 도달했습니다.\n\n코인, 돈, GPU, 쿨러가 초기화됩니다.\n환생 횟수, FORK와 해금한 업그레이드는 유지됩니다.",22,80,356,185,15,White,TextAnchor.MiddleCenter);Button(b,"[ 시스템 재부팅 ]",20,292,360,46,()=>{g.Restart();StopIntro();},Red);}
 // Original opening and tutorial copy, retained from index.html.
 static readonly string[] cutLabels={"SYSTEM BOOT","RIG ONLINE","MARKET LINK","EXPAND RIG","QUANTUM GOAL"},cutTitles={"낡은 채굴실","첫 번째 GPU","가상 코인 시장 접속","더 강한 장비","목표: QUANTUM"},cutArt={"●\nPOWER OFF\n...\nSIGNAL FOUND","▣\nRTX 1090\nTEMP 30°C\nSTATUS : ONLINE","₿ Ξ Ð ✦ Q\nMARKET LINK : CONNECTED\nVOLATILITY : ACTIVE","▣  ▣  ▣\nGPU / COOLING / POWER\nBUILD YOUR RIG","⚛\nRTX 6090 QUANTUM\nREBIRTH PROTOCOL\nLOCKED"},cutText={"불 꺼진 작은 방.\n책상 위에는 오래된 채굴 장비 한 대만 남아 있다.","전원을 넣자 RTX 1090의 팬이 천천히 돌기 시작한다.\n이 한 장이 모든 것의 시작이다.","채굴한 코인은 시장에서 현금으로 바꿀 수 있다.\n하지만 시세는 계속 움직이고, 어떤 코인은 갑자기 폭등하거나 급락한다.","더 좋은 GPU를 사고, 냉각을 강화하고, 새로운 코인을 해금하라.\n작은 랙은 점점 거대한 채굴 시스템으로 변한다.","최종 목표는 RTX 6090 QUANTUM과 환생 프로토콜.\n지금부터 첫 번째 채굴을 시작한다."};
 static readonly string[] tutTitles={"1. GPU를 눌러 채굴","2. 코인을 현금으로 판매","3. GPU 업그레이드","4. 온도와 GPU 쿨링","5. 전력과 오버클럭","6. 계약과 시장 이벤트","7. 환생과 FORK"},tutText={"랙에 장착된 GPU를 클릭하면 코인을 채굴합니다.\n\nGPU가 여러 장이면 클릭 한 번에 장착된 GPU가 모두 같이 채굴합니다.","방 오른쪽 컴퓨터를 누르면 거래소가 열립니다.\n\n채굴한 코인을 현재 게임 시세로 팔아 ₩ 현금을 만들고, 그 돈으로 장비를 구매합니다.","[SHOP]에서 GPU를 구매하거나 [GPU]에서 1번 슬롯 GPU를 업그레이드할 수 있습니다.\n\n상위 GPU를 보유하면 ETHER-X, DOGE-X 같은 새로운 코인도 순서대로 해금됩니다.","채굴과 오버클럭은 GPU 온도를 올립니다.\n\n[COOL]에서 GPU 전용 공랭/수냉을 장착하세요. GPU 하나라도 100°C에 도달하면 시스템이 파산합니다.","[OC]는 채굴 성능을 높이지만 발열도 증가합니다.\n\nGPU 전력 사용량에 따라 실제 게임 현금에서 전기요금이 주기적으로 차감됩니다.","거래소에는 채굴/판매 계약이 있습니다. 목표를 완료하면 현금 보상을 받을 수 있습니다.\n\n랜덤 이벤트로 해금된 특정 코인이 갑자기 급등하거나 급락할 수도 있습니다.","최종 RTX 6090 QUANTUM을 준비하고 환생 조건을 달성하면 FORK를 얻습니다.\n\n환생하면 이번 회차 장비는 초기화되지만 FORK 업그레이드는 남아 다음 회차 성장을 빠르게 해줍니다."};
 void StopIntro(){if(typing!=null)StopCoroutine(typing);typingNow=false;if(intro!=null){intro.gameObject.SetActive(false);Destroy(intro.gameObject);}intro=null;g.IntroPaused=false;}
 void Opening(bool rp){if(!g.S.running)return;Close();replay=rp;introIndex=0;RenderOpening();}
 void RenderOpening(){StopIntro();g.IntroPaused=true;intro=Box(screen,"Opening",0,0,480,854,C("02040a"));var b=Box(intro,"Cutscene",25,148,430,535,Dark,C("303a50"),3);Text(b,cutLabels[introIndex],12,8,300,28,12,Cyan);Button(b,"SKIP",347,8,70,29,FinishOpening,Red,10);Box(b,"Visual",3,44,424,220,introIndex==2?C("241b39"):introIndex==4?C("123e3a"):C("14283e"));Text(b,cutArt[introIndex],18,68,394,176,22,Green,TextAnchor.MiddleCenter);Text(b,cutTitles[introIndex],16,280,398,33,18,Gold);typed=Text(b,"",16,321,398,125,16);fullCaption=cutText[introIndex];typing=StartCoroutine(TypeCaption());Text(b,new string('■',introIndex+1)+new string('□',4-introIndex),16,466,185,40,13,Cyan);Button(b,introIndex==4?"[ 채굴 시작 ]":"[ 계속 ]",260,470,151,42,()=>{if(typingNow){StopCoroutine(typing);typed.text=fullCaption;typingNow=false;}else if(introIndex<4){introIndex++;RenderOpening();}else FinishOpening();});}
 IEnumerator TypeCaption(){typingNow=true;for(int i=0;i<=fullCaption.Length;i++){typed.text=fullCaption.Substring(0,i);yield return new WaitForSecondsRealtime(.022f);}typingNow=false;}
 void FinishOpening(){PlayerPrefs.SetInt("webport_opening",1);PlayerPrefs.Save();StopIntro();if(!replay&&PlayerPrefs.GetInt("webport_tutorial",0)==0)Tutorial();}
 void Tutorial(){if(!g.S.running)return;Close();introIndex=0;RenderTutorial();}
 void RenderTutorial(){StopIntro();g.IntroPaused=true;intro=Box(screen,"Tutorial",0,0,480,854,new Color(.01f,.02f,.05f,.97f));var b=Box(intro,"Tutorial Card",30,155,420,534,Panel,Cyan,4);Text(b,"TUTORIAL "+(introIndex+1)+" / 7",16,13,263,32,12,Cyan);Button(b,"건너뛰기",306,14,98,32,FinishTutorial,Red,11);Text(b,tutTitles[introIndex],20,85,380,55,21,Green,TextAnchor.MiddleCenter);Text(b,tutText[introIndex],26,158,368,231,17);Text(b,new string('■',introIndex+1)+new string('□',6-introIndex),20,407,380,28,14,Cyan,TextAnchor.MiddleCenter);Button(b,"[ 이전 ]",20,463,180,47,introIndex>0?(Action)(()=>{introIndex--;RenderTutorial();}):null,Cyan);Button(b,introIndex==6?"[ 시작 ]":"[ 다음 ]",220,463,180,47,()=>{if(introIndex<6){introIndex++;RenderTutorial();}else FinishTutorial();});}
 void FinishTutorial(){PlayerPrefs.SetInt("webport_tutorial",1);PlayerPrefs.Save();StopIntro();Toast("튜토리얼 완료! GPU를 클릭해 시작하세요.");}
}
[RequireComponent(typeof(CanvasRenderer))]
public class CandleChart:MaskableGraphic {
 public MarketManager market;public string coinId;
 protected override void OnPopulateMesh(VertexHelper vh){vh.Clear();if(market==null)return;var series=market.Series(coinId);if(series==null||series.candles.Count==0)return;var cs=series.candles;float lo=float.MaxValue,hi=float.MinValue;foreach(var c in cs){lo=Mathf.Min(lo,c.low);hi=Mathf.Max(hi,c.high);}float pad=Mathf.Max(Catalog.Coin(coinId).basePrice*.01f,(hi-lo)*.12f);lo-=pad;hi+=pad;float w=rectTransform.rect.width,h=rectTransform.rect.height;Func<float,float> y=p=>h*(p-lo)/(hi-lo);for(int i=0;i<5;i++)Quad(vh,0,h*i/4,w,1,new Color(.21f,.23f,.28f));float step=w/cs.Count;for(int i=0;i<cs.Count;i++){var c=cs[i];float x=(i+.5f)*step;Color color=c.close>=c.open?new Color(1,.38f,.36f):new Color(.31f,.60f,1);Quad(vh,x,y(c.low),1,Mathf.Max(1,y(c.high)-y(c.low)),color);Quad(vh,x-step*.3f,y(Mathf.Min(c.open,c.close)),Mathf.Max(1,step*.6f),Mathf.Max(1,Mathf.Abs(y(c.close)-y(c.open))),color);}}
 void Quad(VertexHelper vh,float x,float y,float w,float h,Color c){int n=vh.currentVertCount;Vector2 o=rectTransform.rect.min;vh.AddVert(new Vector3(x+o.x,y+o.y),c,Vector2.zero);vh.AddVert(new Vector3(x+w+o.x,y+o.y),c,Vector2.zero);vh.AddVert(new Vector3(x+w+o.x,y+h+o.y),c,Vector2.zero);vh.AddVert(new Vector3(x+o.x,y+h+o.y),c,Vector2.zero);vh.AddTriangle(n,n+1,n+2);vh.AddTriangle(n,n+2,n+3);}
}
}
